### ISSUE TITLE
Old Lensfun Data?

### ISSUE THREAD

**Issue by sunman86** [sergiusens/darktable-snap#16]
This snap does not seem to support the latest cameras (Sony Alpha 7R III) which are in the Lensfun list of supported cameras, which are in version 2.4.4. The Lens Correction module does not include the latest cameras.

**Comment by KristijanZic** [comment]
That is probably because Darktable hasn't updated lensfun yet but in the version of Darktable from the universe it is possible to add your own LCP profiles.

[There is a guide in the RawTherapee wiki on how to convert Adobe LPC  to lensfun LPC and add it to the RawTherapee.](http://rawpedia.rawtherapee.com/How_to_get_LCP_and_DCP_profiles)

The same can be added in the Darktable from the universe aka deb as described by Shane Milton [here](https://www.youtube.com/watch?v=tya1U6Ki5Rg).

Or if you say that your camera is already supported by lensfun you could just add the new lenfun database manually.

The issue that I have is that I just don't know where that goes in the snap so I'm as stuck as you are.
@kyrofa pls help :)

**Comment by kyrofa** [comment]
I'm working on this; I want to ship a more updated lensfun (and calibrations) and also allow for folks to supply their own.

**Comment by KristijanZic** [comment]
You Sir are a God!

**Comment by Swissbite** [comment]
I have the same issue: The lensfun db seems outdated. It does not include my Olympus E-M5 Mark II and some lenses.

**Comment by sergiusens** [comment]
I have revamped the snap (3.8.1) to have the latest lensfun data, additionally, I added a shorthand command to easily update the database `darktable.lesfun-update-data`

Hi from a fellow Olympus user!
